# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a612c17aad6dd6a9f2b1b12cd9ed816338b0c908faad48727ecc6d24edd72447b2089a32e69c84df27b907ccdfcaceb9851d484d1421e0c443d305d14cd71068

test:
  secret_key_base: 80adb69c9d439745792d0cfbeae6767efce8dba0373473b7fe8cb6619a4a414e1946e31c995a84b18a10b4bc99a77bbc5b74bb98d534fea0dcd757e0820a1a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
